#Github action to dploy pokemon reveiew api

name: Deploy Pokemon Review API

on:
  workflow_dispatch:

  env:
    AZURE_WEBAPP_NAME: "pokemon-review-api-eastus-dev-001"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnete-version: 8.0.x
        
      - name: Install Dependencies
        run: dotnet restore ./PokemonReviewApp/PokemonReviewApp.csproj

      - name: build
        run: dotnet build ./PokemonReviewApp/PokemonReviewApp.csproj --configuration Release --no-restore

      #Publish 

      - name: Publish
        run: dotnet publish ./PokemonReviewApp/PokemonReviewApp.csproj --configuration Release --no-build --output ./publish

      #Deploy to azure
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.API_PUBLISH_SECRET}}
          package: ./publish